#!/bin/bash

# Author :
# Created :
# Last Modified : 
#
# Description :
#

echo "Hello, ${USER^}"
echo "I will now backup your home directory at, $HOME"

currentdir=$(pwd)
echo "You are running this script from $currentdir "
echo "Therefore, backups will be created at $currentdir"

tar -cf "$currentdir/home_backup_$(date +%d-%m-%Y_%H-%M-%S).tar" $Home 2>/dev/null

echo "Backup completed successfully"

exit 0

